"""Constants for the Commute Tracker integration."""

DOMAIN = "commute_tracker"

BUS_DWELL_SECONDS = 45
DEFAULT_WALK_SECONDS = 240
DEFAULT_PREP_SECONDS = 120
DEFAULT_GRACE_SECONDS = 180
DEFAULT_PREPARE_THRESHOLD_SECONDS = 480

DEFAULT_LINE_STATUS = "Unknown"
DEFAULT_LINE_COLOUR = "#757575"
DEFAULT_LINE_ICON = "mdi:help-circle"

CORRIDOR_UPSTREAM_HORIZON_SECONDS = 600
MIDNIGHT_WRAP_THRESHOLD_SECONDS = 43200
