"""Constants for the Commute Tracker integration."""

DOMAIN = "commute_tracker"
DEFAULT_WALK_SECONDS = 240
DEFAULT_PREP_SECONDS = 120
DEFAULT_GRACE_FRACTION = 0.25
DEFAULT_GRACE_SECONDS = 60
DEFAULT_PREPARE_THRESHOLD_SECONDS = 480

DEFAULT_LINE_STATUS = "Unknown"
DEFAULT_LINE_COLOUR = "#757575"
DEFAULT_LINE_ICON = "mdi:help-circle"

DEFAULT_ROLLUP_STRATEGY = "late_with_buffer"
DEFAULT_ROUTE_LATE_BUFFER_SECONDS = 300

CORRIDOR_UPSTREAM_HORIZON_SECONDS = 600
MIDNIGHT_WRAP_THRESHOLD_SECONDS = 43200
